Fix up install issues

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE GETTEXT_PACKAGE USE_NLS MSGFMT GMSGFMT XGETTEXT CATALOGS CATOBJEXT DATADIRNAME GMOFILES INSTOBJEXT INTLLIBS PO_IN_DATADIR_TRUE PO_IN_DATADIR_FALSE POFILES POSUB MKINSTALLDIRS build build_cpu build_vendor build_os host host_cpu host_vendor host_os SED LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL PKG_CONFIG ac_pt_PKG_CONFIG GLIB_CFLAGS GLIB_LIBS GECKO_CFLAGS GECKO_LIBS GECKO_HOME DBUS_CFLAGS DBUS_LIBS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE GETTEXT_PACKAGE USE_NLS MSGFMT GMSGFMT XGETTEXT CATALOGS CATOBJEXT DATADIRNAME GMOFILES INSTOBJEXT INTLLIBS PO_IN_DATADIR_TRUE PO_IN_DATADIR_FALSE POFILES POSUB MKINSTALLDIRS build build_cpu build_vendor build_os host host_cpu host_vendor host_os SED LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL PKG_CONFIG ac_pt_PKG_CONFIG GLIB_CFLAGS GLIB_LIBS GECKO_CFLAGS GECKO_LIBS GECKO_HOME GECKO_XPIDL GECKO_IDLDIR DBUS_CFLAGS DBUS_LIBS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -22461,12 +22461,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GECKO_CFLAGS="$GECKO_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"mozilla-plugin\"") >&5
-  ($PKG_CONFIG --exists --print-errors "mozilla-plugin") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"mozilla-plugin mozilla-xpcom\"") >&5
+  ($PKG_CONFIG --exists --print-errors "mozilla-plugin mozilla-xpcom") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GECKO_CFLAGS=`$PKG_CONFIG --cflags "mozilla-plugin" 2>/dev/null`
+  pkg_cv_GECKO_CFLAGS=`$PKG_CONFIG --cflags "mozilla-plugin mozilla-xpcom" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -22479,12 +22479,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GECKO_LIBS="$GECKO_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"mozilla-plugin\"") >&5
-  ($PKG_CONFIG --exists --print-errors "mozilla-plugin") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"mozilla-plugin mozilla-xpcom\"") >&5
+  ($PKG_CONFIG --exists --print-errors "mozilla-plugin mozilla-xpcom") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GECKO_LIBS=`$PKG_CONFIG --libs "mozilla-plugin" 2>/dev/null`
+  pkg_cv_GECKO_LIBS=`$PKG_CONFIG --libs "mozilla-plugin mozilla-xpcom" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -22503,9 +22503,9 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        GECKO_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "mozilla-plugin"`
+	        GECKO_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "mozilla-plugin mozilla-xpcom"`
         else
-	        GECKO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "mozilla-plugin"`
+	        GECKO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "mozilla-plugin mozilla-xpcom"`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$GECKO_PKG_ERRORS" >&5
@@ -22522,7 +22522,10 @@ else
 	GECKO_LIBS=$pkg_cv_GECKO_LIBS
         echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-	GECKO_HOME=`$PKG_CONFIG --variable=libdir mozilla-plugin`
+
+    GECKO_HOME=`$PKG_CONFIG --variable=libdir mozilla-plugin`
+    GECKO_IDLDIR=`$PKG_CONFIG --variable=idldir mozilla-xpcom`
+
 fi
 
 if test "$GECKO_CFLAGS" = ""; then
@@ -22597,7 +22600,10 @@ else
 	GECKO_LIBS=$pkg_cv_GECKO_LIBS
         echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-	GECKO_HOME=`$PKG_CONFIG --variable=libdir firefox-plugin`
+
+    GECKO_HOME=`$PKG_CONFIG --variable=libdir firefox-plugin`
+    GECKO_IDLDIR=`$PKG_CONFIG --variable=idldir firefox-xpcom`
+
 fi
 fi
 
@@ -22612,12 +22618,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GECKO_CFLAGS="$GECKO_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"seamonkey-plugin\"") >&5
-  ($PKG_CONFIG --exists --print-errors "seamonkey-plugin") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"seamonkey-plugin seamonkey-xpcom\"") >&5
+  ($PKG_CONFIG --exists --print-errors "seamonkey-plugin seamonkey-xpcom") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GECKO_CFLAGS=`$PKG_CONFIG --cflags "seamonkey-plugin" 2>/dev/null`
+  pkg_cv_GECKO_CFLAGS=`$PKG_CONFIG --cflags "seamonkey-plugin seamonkey-xpcom" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -22630,12 +22636,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GECKO_LIBS="$GECKO_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"seamonkey-plugin\"") >&5
-  ($PKG_CONFIG --exists --print-errors "seamonkey-plugin") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"seamonkey-plugin seamonkey-xpcom\"") >&5
+  ($PKG_CONFIG --exists --print-errors "seamonkey-plugin seamonkey-xpcom") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GECKO_LIBS=`$PKG_CONFIG --libs "seamonkey-plugin" 2>/dev/null`
+  pkg_cv_GECKO_LIBS=`$PKG_CONFIG --libs "seamonkey-plugin seamonkey-xpcom" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -22654,9 +22660,9 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        GECKO_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "seamonkey-plugin"`
+	        GECKO_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "seamonkey-plugin seamonkey-xpcom"`
         else
-	        GECKO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "seamonkey-plugin"`
+	        GECKO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "seamonkey-plugin seamonkey-xpcom"`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$GECKO_PKG_ERRORS" >&5
@@ -22673,7 +22679,10 @@ else
 	GECKO_LIBS=$pkg_cv_GECKO_LIBS
         echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-	GECKO_HOME=`$PKG_CONFIG --variable=libdir seamonkey-plugin`
+
+    GECKO_HOME=`$PKG_CONFIG --variable=libdir seamonkey-plugin`
+    GECKO_IDLDIR=`$PKG_CONFIG --variable=idldir seamonkey-xpcom`
+
 fi
 fi
 
@@ -22688,12 +22697,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GECKO_CFLAGS="$GECKO_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xulrunner-plugin\"") >&5
-  ($PKG_CONFIG --exists --print-errors "xulrunner-plugin") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xulrunner-plugin xulrunner-xpcom\"") >&5
+  ($PKG_CONFIG --exists --print-errors "xulrunner-plugin xulrunner-xpcom") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GECKO_CFLAGS=`$PKG_CONFIG --cflags "xulrunner-plugin" 2>/dev/null`
+  pkg_cv_GECKO_CFLAGS=`$PKG_CONFIG --cflags "xulrunner-plugin xulrunner-xpcom" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -22706,12 +22715,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GECKO_LIBS="$GECKO_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xulrunner-plugin\"") >&5
-  ($PKG_CONFIG --exists --print-errors "xulrunner-plugin") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xulrunner-plugin xulrunner-xpcom\"") >&5
+  ($PKG_CONFIG --exists --print-errors "xulrunner-plugin xulrunner-xpcom") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GECKO_LIBS=`$PKG_CONFIG --libs "xulrunner-plugin" 2>/dev/null`
+  pkg_cv_GECKO_LIBS=`$PKG_CONFIG --libs "xulrunner-plugin xulrunner-xpcom" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -22730,9 +22739,9 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        GECKO_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "xulrunner-plugin"`
+	        GECKO_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "xulrunner-plugin xulrunner-xpcom"`
         else
-	        GECKO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xulrunner-plugin"`
+	        GECKO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xulrunner-plugin xulrunner-xpcom"`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$GECKO_PKG_ERRORS" >&5
@@ -22749,7 +22758,10 @@ else
 	GECKO_LIBS=$pkg_cv_GECKO_LIBS
         echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-	GECKO_HOME=`$PKG_CONFIG --variable=libdir xulrunner-plugin`
+
+    GECKO_HOME=`$PKG_CONFIG --variable=libdir xulrunner-plugin`
+    GECKO_IDLDIR=`$PKG_CONFIG --variable=idldir xulrunner-xpcom`
+
 fi
 fi
 
@@ -22764,12 +22776,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GECKO_CFLAGS="$GECKO_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"iceape-plugin\"") >&5
-  ($PKG_CONFIG --exists --print-errors "iceape-plugin") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"iceape-plugin iceape-xpcom\"") >&5
+  ($PKG_CONFIG --exists --print-errors "iceape-plugin iceape-xpcom") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GECKO_CFLAGS=`$PKG_CONFIG --cflags "iceape-plugin" 2>/dev/null`
+  pkg_cv_GECKO_CFLAGS=`$PKG_CONFIG --cflags "iceape-plugin iceape-xpcom" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -22782,12 +22794,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GECKO_LIBS="$GECKO_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"iceape-plugin\"") >&5
-  ($PKG_CONFIG --exists --print-errors "iceape-plugin") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"iceape-plugin iceape-xpcom\"") >&5
+  ($PKG_CONFIG --exists --print-errors "iceape-plugin iceape-xpcom") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GECKO_LIBS=`$PKG_CONFIG --libs "iceape-plugin" 2>/dev/null`
+  pkg_cv_GECKO_LIBS=`$PKG_CONFIG --libs "iceape-plugin iceape-xpcom" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -22806,9 +22818,9 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        GECKO_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "iceape-plugin"`
+	        GECKO_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "iceape-plugin iceape-xpcom"`
         else
-	        GECKO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "iceape-plugin"`
+	        GECKO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "iceape-plugin iceape-xpcom"`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$GECKO_PKG_ERRORS" >&5
@@ -22825,8 +22837,66 @@ else
 	GECKO_LIBS=$pkg_cv_GECKO_LIBS
         echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-	GECKO_HOME=`$PKG_CONFIG --variable=libdir iceape-plugin`
+
+    GECKO_HOME=`$PKG_CONFIG --variable=libdir iceape-plugin`
+    GECKO_IDLDIR=`$PKG_CONFIG --variable=idldir iceape-xpcom`
+
 fi
+fi
+
+
+
+
+
+# Extract the first word of "xpidl", so it can be a program name with args.
+set dummy xpidl; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_GECKO_XPIDL+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $GECKO_XPIDL in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_GECKO_XPIDL="$GECKO_XPIDL" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+as_dummy="$GECKO_HOME:$PATH"
+for as_dir in $as_dummy
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_GECKO_XPIDL="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_GECKO_XPIDL" && ac_cv_path_GECKO_XPIDL="no"
+  ;;
+esac
+fi
+GECKO_XPIDL=$ac_cv_path_GECKO_XPIDL
+
+if test -n "$GECKO_XPIDL"; then
+  echo "$as_me:$LINENO: result: $GECKO_XPIDL" >&5
+echo "${ECHO_T}$GECKO_XPIDL" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test "x$GECKO_XPIDL" = "xno"; then
+	{ { echo "$as_me:$LINENO: error: xpidl compiler not found" >&5
+echo "$as_me: error: xpidl compiler not found" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "x$GECKO_IDLDIR" = "x"; then
+    GECKO_IDLDIR="`echo $GECKO_HOME | sed -e s!lib!share/idl!`"
 fi
 
 
@@ -23710,6 +23780,8 @@ s,@GLIB_LIBS@,$GLIB_LIBS,;t t
 s,@GECKO_CFLAGS@,$GECKO_CFLAGS,;t t
 s,@GECKO_LIBS@,$GECKO_LIBS,;t t
 s,@GECKO_HOME@,$GECKO_HOME,;t t
+s,@GECKO_XPIDL@,$GECKO_XPIDL,;t t
+s,@GECKO_IDLDIR@,$GECKO_IDLDIR,;t t
 s,@DBUS_CFLAGS@,$DBUS_CFLAGS,;t t
 s,@DBUS_LIBS@,$DBUS_LIBS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
