64bit libdir set correctly

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -730,6 +730,8 @@ GLIB_CFLAGS
 GLIB_LIBS
 GECKO_CFLAGS
 GECKO_LIBS
+NSPR_CFLAGS
+NSPR_LIBS
 GECKO_HOME
 GECKO_XPIDL
 GECKO_IDLDIR
@@ -762,6 +764,8 @@ GLIB_CFLAGS
 GLIB_LIBS
 GECKO_CFLAGS
 GECKO_LIBS
+NSPR_CFLAGS
+NSPR_LIBS
 DBUS_CFLAGS
 DBUS_LIBS
 GCONF_CFLAGS
@@ -1374,6 +1378,8 @@ Some influential environment variables:
   GECKO_CFLAGS
               C compiler flags for GECKO, overriding pkg-config
   GECKO_LIBS  linker flags for GECKO, overriding pkg-config
+  NSPR_CFLAGS C compiler flags for NSPR, overriding pkg-config
+  NSPR_LIBS   linker flags for NSPR, overriding pkg-config
   DBUS_CFLAGS C compiler flags for DBUS, overriding pkg-config
   DBUS_LIBS   linker flags for DBUS, overriding pkg-config
   GCONF_CFLAGS
@@ -8793,6 +8799,84 @@ fi
 fi
 
 
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for NSPR" >&5
+echo $ECHO_N "checking for NSPR... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$NSPR_CFLAGS"; then
+        pkg_cv_NSPR_CFLAGS="$NSPR_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"nspr\"") >&5
+  ($PKG_CONFIG --exists --print-errors "nspr") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_NSPR_CFLAGS=`$PKG_CONFIG --cflags "nspr" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$NSPR_LIBS"; then
+        pkg_cv_NSPR_LIBS="$NSPR_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"nspr\"") >&5
+  ($PKG_CONFIG --exists --print-errors "nspr") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_NSPR_LIBS=`$PKG_CONFIG --libs "nspr" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        NSPR_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "nspr"`
+        else
+	        NSPR_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "nspr"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$NSPR_PKG_ERRORS" >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+                { echo "$as_me:$LINENO: WARNING: nspr not found, may not be needed" >&5
+echo "$as_me: WARNING: nspr not found, may not be needed" >&2;}
+elif test $pkg_failed = untried; then
+	{ echo "$as_me:$LINENO: WARNING: nspr not found, may not be needed" >&5
+echo "$as_me: WARNING: nspr not found, may not be needed" >&2;}
+else
+	NSPR_CFLAGS=$pkg_cv_NSPR_CFLAGS
+	NSPR_LIBS=$pkg_cv_NSPR_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+    libdir=`$PKG_CONFIG --variable=libdir nspr`
+
+fi
+
+
+
+
 
 
 
@@ -9964,6 +10048,8 @@ GLIB_CFLAGS!$GLIB_CFLAGS$ac_delim
 GLIB_LIBS!$GLIB_LIBS$ac_delim
 GECKO_CFLAGS!$GECKO_CFLAGS$ac_delim
 GECKO_LIBS!$GECKO_LIBS$ac_delim
+NSPR_CFLAGS!$NSPR_CFLAGS$ac_delim
+NSPR_LIBS!$NSPR_LIBS$ac_delim
 GECKO_HOME!$GECKO_HOME$ac_delim
 GECKO_XPIDL!$GECKO_XPIDL$ac_delim
 GECKO_IDLDIR!$GECKO_IDLDIR$ac_delim
@@ -9980,7 +10066,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 34; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 36; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
