more --with-xulrunner-sdk fixes

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -8252,8 +8252,8 @@ fi
 if test "${with_xulrunner_sdk+set}" = set; then
   withval=$with_xulrunner_sdk;
 	XULRUNNER_SDK_PREFIX=$with_xulrunner_sdk
-	GECKO_CFLAGS="-I$XULRUNNER_SDK_PREFIX/include"
-	GECKO_LIBS="$XULRUNNER_SDK_PREFIX/lib -lxpcomglue_s -lxul -lxpcom -lplds4 -lplc4 -lnspr4 -lpthread -ldl"
+	GECKO_CFLAGS="-I$XULRUNNER_SDK_PREFIX/include -I$XULRUNNER_SDK_PREFIX/include/plugin -I$XULRUNNER_SDK_PREFIX/include/nspr -I$XULRUNNER_SDK_PREFIX/include/xpcom -I$XULRUNNER_SDK_PREFIX/include/string -I$XULRUNNER_SDK_PREFIX/include/java"
+	GECKO_LIBS="-L$XULRUNNER_SDK_PREFIX/lib -lxpcomglue_s -lxul -lxpcom -lplds4 -lplc4 -lnspr4 -lpthread -ldl"
 	GECKO_HOME="$XULRUNNER_SDK_PREFIX/bin"
 	GECKO_IDLDIR="$XULRUNNER_SDK_PREFIX/idl"
 
@@ -8939,8 +8939,8 @@ fi
 
 
 if test "x$GECKO_XPIDL" = "xno"; then
-	{ { echo "$as_me:$LINENO: error: xpidl compiler not found" >&5
-echo "$as_me: error: xpidl compiler not found" >&2;}
+	{ { echo "$as_me:$LINENO: error: xpidl compiler not found in $GECKO_HOME:$PATH" >&5
+echo "$as_me: error: xpidl compiler not found in $GECKO_HOME:$PATH" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
